# Generated by Django 3.0.2 on 2020-01-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospiceWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
    ]
